# Import libraries

In [1]:
import pandas as pd
import os
import shutil
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
import threading
from typing import Tuple
from tqdm import tqdm

import sys
sys.path.append('..')
from utils.audio_util import convert_mp3_to_flac, resample_audios, trim_silence_with_vad, normalize_audio_files
from utils.file_util import recursive_copy

# Moving files to new directory

In [2]:
df = pd.read_csv("../data/raw/thai-central/thai-central_mapping.csv")

In [3]:
AUDIO_BASE_DIR = "../data/raw/thai-central/audio_v2"
DEST_DIR = "../data/converted/thai-central-to-vctk"
AUDIO_DEST_DIR = os.path.join(DEST_DIR, "wav16")
TXT_DEST_DIR = os.path.join(DEST_DIR, "txt")

In [4]:
# Add full path column
df['full_path'] = df['public_name'].apply(lambda x: os.path.join(AUDIO_BASE_DIR, x))

# Filter existing files
df_filtered = df[df['full_path'].apply(os.path.exists)].copy()

# Count files per speaker
speaker_counts = df_filtered['speaker_id'].value_counts()
valid_speakers = speaker_counts[speaker_counts >= 100].index

# Filter speakers with >= 100 files
df_filtered = df_filtered[df_filtered['speaker_id'].isin(valid_speakers)]

In [5]:
# Create new speaker ID mapping
sorted_speakers = speaker_counts[speaker_counts >= 100].sort_values().index
speaker_mapping = {
    spk: f'tc{i+1:04d}' 
    for i, spk in enumerate(sorted_speakers)
}

# Add new speaker ID column
df_filtered['new_speaker_id'] = df_filtered['speaker_id'].map(speaker_mapping)
df_filtered

,speaker_id,original_name,public_name,full_path,new_speaker_id
3,spk-560353791001250275300,60f7422cf22f3d24deb858fd_1627814081674.wav,train_audio02/thai-central_000003.mp3,../data/raw/thai-central/audio_v2/train_audio0...,tc0776
5,spk8789214662434341888000,611bdfa7cf5abe28e3190dab_1637558034204.wav,train_audio12/thai-central_000005.mp3,../data/raw/thai-central/audio_v2/train_audio1...,tc0675
6,spk2272676593238898160000,6107d2adfb309b3360224bb3_1637129050946.wav,train_audio06/thai-central_000006.mp3,../data/raw/thai-central/audio_v2/train_audio0...,tc0571
7,spk-659303002028011164800,60f7422cf22f3d24deb85922_1628183509033.wav,train_audio01/thai-central_000007.mp3,../data/raw/thai-central/audio_v2/train_audio0...,tc0898
8,spk5308879110509872434000,60f7422cf22f3d24deb858ff_1628702261034.wav,train_audio02/thai-central_000008.mp3,../data/raw/thai-central/audio_v2/train_audio0...,tc0965
...,...,...,...,...,...
433806,spk-717737201021391723000,611be1b6cf5abe28e3191fe0_1636618869118.wav,train_audio05/thai-central_433806.mp3,../data/raw/thai-central/audio_v2/train_audio0...,tc0649
433808,spk8339279944661639402000,60f7422cf22f3d24deb85917_1629169814235.wav,train_audio02/thai-central_433808.mp3,../data/raw/thai-central/audio_v2/train_audio0...,tc0923
433811,spk7617813596557544310000,6107d2adfb309b3360224ba8_1637550218939.wav,train_audio12/thai-central_433811.mp3,../data/raw/thai-central/audio_v2/train_audio1...,tc0656
433812,spk-581523479174861464600,611be1b6cf5abe28e3191fd3_1629719575649.wav,train_audio04/thai-central_433812.mp3,../data/raw/thai-central/audio_v2/train_audio0...,tc0683
433813,spk7283136930844492645000,60f7422cf22f3d24deb85921_1630115389388.wav,train_audio02/thai-central_433813.mp3,../data/raw/thai-central/audio_v2/train_audio0...,tc0930

In [6]:
df_train = pd.read_csv("../data/raw/thai-central/train.csv")
df_dev = pd.read_csv("../data/raw/thai-central/dev.csv")

df_all = pd.concat([df_train, df_dev], ignore_index=True)
df_all['sentence'] = df_all['sentence'].apply(lambda x: "".join(x.split()))
df_all['audio'] = df_all['audio'].apply(lambda x: os.path.join(AUDIO_BASE_DIR, x))
df_all

,utterance,sentence,audio
0,thai-central_000000,ทีมจากอิสราเอลไม่ควรได้เป็นเจ้าบ้านในเกมยูฟ่าคัพ,../data/raw/thai-central/audio_v2/train_audio1...
1,thai-central_000001,แต่พอไหมอะไรคือแต้อีบ็อบฮ่าฮ่ากูพิมพ์ผิดไหมล่ะ...,../data/raw/thai-central/audio_v2/train_audio0...
2,thai-central_000003,ทุกสิ่งทุกอย่างจะราบรื่น,../data/raw/thai-central/audio_v2/train_audio0...
3,thai-central_000005,เร็วหันมองเวลาตั้งกระทู้,../data/raw/thai-central/audio_v2/train_audio1...
4,thai-central_000006,มีขนาดหนาและใหญ่กว่าเกร็ดปลาทั่วไปจนเหมือนเครื...,../data/raw/thai-central/audio_v2/train_audio0...
...,...,...,...
341134,thai-central_433292,มีของทั้งหมดเป็นจำนวนหนึ่งหมื่นหนึ่งพันกระป๋องค่ะ,../data/raw/thai-central/audio_v2/dev_audio00/...
341135,thai-central_433304,บ้านงิ้วงามหมู่สี่มีอาณาเขตติดต่อกับหมู่บ้านใก...,../data/raw/thai-central/audio_v2/dev_audio00/...
341136,thai-central_433457,กองทัพเรือหมายถึงกองกำลังทางทหารที่ปฏิบัติการท...,../data/raw/thai-central/audio_v2/dev_audio00/...
341137,thai-central_433700,กรมอู่ทหารเรือ,../data/raw/thai-central/audio_v2/dev_audio00/...
341138,thai-central_433793,ตาเบอร์ศูนย์สองสิบแปดสามหนึ่งเก้าหกห้าสี่ครับ,../data/raw/thai-central/audio_v2/dev_audio00/...

In [7]:
audio2sentence = dict(zip(df_all['audio'], df_all['sentence']))

In [8]:
# Thread-safe set for character collection
all_chars = set()
chars_lock = threading.Lock()

# Thread-safe list for tracking skipped files
skip_files = []
skip_lock = threading.Lock()

def process_file_pair(args: Tuple[str, str, str, str]) -> None:
    """Process a single pair of audio and text files"""
    speaker_id, src_path, dest_audio_path, dest_txt_path = args
    try:
        # Create speaker directories
        speaker_wav_dir = os.path.join(AUDIO_DEST_DIR, speaker_id)
        speaker_txt_dir = os.path.join(TXT_DEST_DIR, speaker_id)
        os.makedirs(speaker_wav_dir, exist_ok=True)
        os.makedirs(speaker_txt_dir, exist_ok=True)
        
        # Process audio
        dest_filename = os.path.splitext(os.path.basename(dest_audio_path))[0] + '_mic1.flac'
        dest_path = os.path.join(speaker_wav_dir, dest_filename)
        
        if not convert_mp3_to_flac(src_path, dest_path):
            raise Exception("Failed to convert audio")
        
        # Create empty text file and collect characters
        base_filename = os.path.splitext(dest_filename)[0]
        txt_filename = f"{base_filename}.txt"
        txt_path = os.path.join(speaker_txt_dir, txt_filename)
        
        # In this case we're creating empty text files
        # Modify this part if you need to process actual text content
        with open(txt_path, 'w', encoding='utf-8') as f:
            f.write(audio2sentence[src_path])

        # Collect characters
        with chars_lock:
            all_chars.update(audio2sentence[src_path])
            
    except Exception as e:
        print(f"Error processing file {src_path}: {e}")
        with skip_lock:
            skip_files.append(src_path)

# Remove existing directories if they exist
if os.path.exists(DEST_DIR):
    print("Clearing destination folder")
    shutil.rmtree(DEST_DIR)

# Create necessary directories
os.makedirs(AUDIO_DEST_DIR, exist_ok=True)
os.makedirs(TXT_DEST_DIR, exist_ok=True)

# Create processing arguments
process_args = [
    (row['new_speaker_id'], row['full_path'], 
        os.path.join(AUDIO_DEST_DIR, row['new_speaker_id'], os.path.basename(row['public_name'])),
        os.path.join(TXT_DEST_DIR, row['new_speaker_id'], os.path.basename(row['public_name'])))
    for _, row in df_filtered.iterrows()
]

# Process files in parallel with progress bar
max_workers = os.cpu_count()
with ThreadPoolExecutor(max_workers=max_workers) as executor:
    list(tqdm(
        executor.map(process_file_pair, process_args),
        total=len(process_args),
        desc=f"Processing files (using {max_workers} workers)"
    ))

# Print results
print(f"Processed {len(df_filtered) - len(skip_files)} file pairs")
print(f"Skipped {len(skip_files)} pairs")
print(f"Unique characters found: {''.join(sorted(all_chars))}")

Processing files (using 16 workers): 100%|██████████| 225028/225028 [53:34<00:00, 70.00it/s]

Processed 225028 file pairs
Skipped 0 pairs
Unique characters found: กขคฆงจฉชซฌญฎฏฐฑฒณดตถทธนบปผฝพฟภมยรฤลวศษสหฬอฮฯะัาำิีึืุูเแโใไ็่้๊๋์

# Save metadata

In [9]:
DEST_DIR = Path(DEST_DIR)

# Write character files
sorted_chars = sorted(all_chars)
with open(DEST_DIR / 'all_chars_unicode.txt', 'w') as f:
   f.write(''.join(c.encode('unicode_escape').decode('ascii') for c in sorted_chars))
   
with open(DEST_DIR / 'all_chars.txt', 'w') as f:
   f.write(''.join(sorted_chars))

# Resample, trim, and normalize audio

In [10]:
# Create destination directory if it doesn't exist
os.makedirs("../data/converted/thai-central-to-vctk/wav16_silence_trimmed", exist_ok=True)

# Copy all files from wav16 to wav16_silence_trimmed
src_dir = "../data/converted/thai-central-to-vctk/wav16"
dst_dir = "../data/converted/thai-central-to-vctk/wav16_silence_trimmed"

recursive_copy(src_dir, dst_dir)

In [11]:
# Resample all files in wav16_silence_trimmed to 16kHz
SAMPLE_RATE = 16000
NUM_RESAMPLE_THREADS = 8

resample_audios(
  input_folders=dst_dir,
  file_ext="flac",
  sample_rate=SAMPLE_RATE,
  n_jobs=NUM_RESAMPLE_THREADS
)

Resampling the audio files...
Found 225028 files...

100%|██████████| 225028/225028 [03:25<00:00, 1092.91it/s]

Done !

In [12]:
# Trim silence at the beginning and end of each audio file
trim_silence_with_vad(
  input_folder=dst_dir,
  file_extension="flac",
)

Downloading: "https://github.com/snakers4/silero-vad/zipball/master" to /home/ming/.cache/torch/hub/master.zip

Found 225028 .flac files to process

Processing files:   2%|▏         | 4005/225028 [06:58<9:38:20,  6.37it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0171/thai-central_409359_mic1.flac probably does not have speech please check it !!

Processing files:   2%|▏         | 4155/225028 [07:16<7:50:27,  7.82it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0391/thai-central_155337_mic1.flac probably does not have speech please check it !!

Processing files:   2%|▏         | 4237/225028 [07:23<4:12:43, 14.56it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0391/thai-central_366389_mic1.flac probably does not have speech please check it !!

Processing files:   2%|▏         | 4355/225028 [07:45<11:44:32,  5.22it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0199/thai-central_200652_mic1.flac probably does not have speech please check it !!

Processing files:   3%|▎         | 6546/225028 [11:51<7:14:49,  8.37it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0930/thai-central_098678_mic1.flac probably does not have speech please check it !!

Processing files:   8%|▊         | 18062/225028 [33:17<10:00:09,  5.75it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0520/thai-central_269644_mic1.flac probably does not have speech please check it !!

Processing files:   8%|▊         | 18402/225028 [34:11<8:03:59,  7.12it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0519/thai-central_255514_mic1.flac probably does not have speech please check it !!

Processing files:  15%|█▍        | 33292/225028 [1:02:39<4:06:58, 12.94it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0861/thai-central_039311_mic1.flac probably does not have speech please check it !!

Processing files:  15%|█▍        | 33426/225028 [1:02:50<4:31:36, 11.76it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0861/thai-central_316261_mic1.flac probably does not have speech please check it !!

Processing files:  17%|█▋        | 38481/225028 [1:12:50<3:48:33, 13.60it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0248/thai-central_004504_mic1.flac probably does not have speech please check it !!

Processing files:  18%|█▊        | 40789/225028 [1:18:08<3:23:15, 15.11it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0877/thai-central_072016_mic1.flac probably does not have speech please check it !!

Processing files:  18%|█▊        | 41074/225028 [1:18:36<2:34:27, 19.85it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0622/thai-central_145944_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0622/thai-central_037437_mic1.flac probably does not have speech please check it !!

Processing files:  18%|█▊        | 41118/225028 [1:18:37<1:31:41, 33.43it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0622/thai-central_252234_mic1.flac probably does not have speech please check it !!

Processing files:  18%|█▊        | 41142/225028 [1:18:38<1:10:19, 43.58it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0622/thai-central_073788_mic1.flac probably does not have speech please check it !!

Processing files:  18%|█▊        | 41155/225028 [1:18:38<1:59:21, 25.68it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0622/thai-central_338004_mic1.flac probably does not have speech please check it !!

Processing files:  18%|█▊        | 41208/225028 [1:18:41<1:36:35, 31.72it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0622/thai-central_376193_mic1.flac probably does not have speech please check it !!

Processing files:  18%|█▊        | 41219/225028 [1:18:41<1:37:24, 31.45it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0622/thai-central_305592_mic1.flac probably does not have speech please check it !!

Processing files:  18%|█▊        | 41242/225028 [1:18:42<2:15:30, 22.60it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0622/thai-central_090435_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0622/thai-central_111003_mic1.flac probably does not have speech please check it !!

Processing files:  18%|█▊        | 41289/225028 [1:18:44<2:25:56, 20.98it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0622/thai-central_055018_mic1.flac probably does not have speech please check it !!

Processing files:  18%|█▊        | 41293/225028 [1:18:44<2:10:27, 23.47it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0622/thai-central_114874_mic1.flac probably does not have speech please check it !!

Processing files:  20%|█▉        | 43896/225028 [1:23:11<4:52:53, 10.31it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0260/thai-central_142784_mic1.flac probably does not have speech please check it !!

Processing files:  20%|██        | 46064/225028 [1:27:22<6:06:07,  8.15it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0659/thai-central_285973_mic1.flac probably does not have speech please check it !!

Processing files:  21%|██        | 46134/225028 [1:27:33<5:36:05,  8.87it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0659/thai-central_084921_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0659/thai-central_255265_mic1.flac probably does not have speech please check it !!

Processing files:  21%|██        | 47568/225028 [1:30:27<5:26:37,  9.06it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0717/thai-central_040274_mic1.flac probably does not have speech please check it !!

Processing files:  24%|██▍       | 53609/225028 [1:42:38<9:35:35,  4.96it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0858/thai-central_399226_mic1.flac probably does not have speech please check it !!

Processing files:  25%|██▌       | 56494/225028 [1:48:05<4:26:13, 10.55it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0321/thai-central_278966_mic1.flac probably does not have speech please check it !!

Processing files:  25%|██▌       | 56622/225028 [1:48:17<3:47:49, 12.32it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0772/thai-central_339858_mic1.flac probably does not have speech please check it !!

Processing files:  28%|██▊       | 62083/225028 [1:58:49<7:26:21,  6.08it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0366/thai-central_065119_mic1.flac probably does not have speech please check it !!

Processing files:  28%|██▊       | 62396/225028 [1:59:38<4:22:05, 10.34it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0871/thai-central_025337_mic1.flac probably does not have speech please check it !!

Processing files:  29%|██▊       | 64219/225028 [2:03:25<3:45:46, 11.87it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0807/thai-central_293938_mic1.flac probably does not have speech please check it !!

Processing files:  29%|██▉       | 65571/225028 [2:06:24<2:45:26, 16.06it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0921/thai-central_360122_mic1.flac probably does not have speech please check it !!

Processing files:  31%|███▏      | 70679/225028 [2:15:57<5:58:02,  7.18it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0374/thai-central_070543_mic1.flac probably does not have speech please check it !!

Processing files:  33%|███▎      | 74095/225028 [2:21:59<3:23:25, 12.37it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0980/thai-central_055252_mic1.flac probably does not have speech please check it !!

Processing files:  37%|███▋      | 82391/225028 [2:36:38<5:08:07,  7.72it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0341/thai-central_151396_mic1.flac probably does not have speech please check it !!

Processing files:  37%|███▋      | 83330/225028 [2:38:19<3:11:37, 12.32it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0564/thai-central_057156_mic1.flac probably does not have speech please check it !!

Processing files:  37%|███▋      | 83364/225028 [2:38:21<2:11:33, 17.95it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0564/thai-central_267745_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0564/thai-central_042155_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0564/thai-central_099840_mic1.flac probably does not have speech please check it !!

Processing files:  37%|███▋      | 83377/225028 [2:38:22<2:28:10, 15.93it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0564/thai-central_369949_mic1.flac probably does not have speech please check it !!

Processing files:  37%|███▋      | 83384/225028 [2:38:23<2:31:12, 15.61it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0564/thai-central_226956_mic1.flac probably does not have speech please check it !!

Processing files:  37%|███▋      | 83409/225028 [2:38:24<2:25:54, 16.18it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0564/thai-central_031585_mic1.flac probably does not have speech please check it !!

Processing files:  37%|███▋      | 83428/225028 [2:38:25<2:07:06, 18.57it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0564/thai-central_283135_mic1.flac probably does not have speech please check it !!

Processing files:  37%|███▋      | 83435/225028 [2:38:26<2:37:54, 14.95it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0564/thai-central_064990_mic1.flac probably does not have speech please check it !!

Processing files:  37%|███▋      | 83469/225028 [2:38:28<3:23:48, 11.58it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0564/thai-central_029005_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0564/thai-central_384610_mic1.flac probably does not have speech please check it !!

Processing files:  37%|███▋      | 83489/225028 [2:38:30<3:16:34, 12.00it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0564/thai-central_245553_mic1.flac probably does not have speech please check it !!

Processing files:  37%|███▋      | 83503/225028 [2:38:31<2:35:24, 15.18it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0564/thai-central_053789_mic1.flac probably does not have speech please check it !!

Processing files:  38%|███▊      | 85306/225028 [2:41:53<3:32:04, 10.98it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0372/thai-central_072932_mic1.flac probably does not have speech please check it !!

Processing files:  38%|███▊      | 85379/225028 [2:42:02<4:39:55,  8.31it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0412/thai-central_108006_mic1.flac probably does not have speech please check it !!

Processing files:  38%|███▊      | 85433/225028 [2:42:10<5:17:07,  7.34it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0412/thai-central_215540_mic1.flac probably does not have speech please check it !!

Processing files:  38%|███▊      | 85476/225028 [2:42:16<3:25:01, 11.34it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0412/thai-central_346689_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0412/thai-central_319404_mic1.flac probably does not have speech please check it !!

Processing files:  38%|███▊      | 85500/225028 [2:42:19<4:26:18,  8.73it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0412/thai-central_082706_mic1.flac probably does not have speech please check it !!

Processing files:  39%|███▉      | 88366/225028 [2:47:40<3:37:01, 10.50it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0297/thai-central_183802_mic1.flac probably does not have speech please check it !!

Processing files:  39%|███▉      | 88581/225028 [2:47:58<3:32:11, 10.72it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0965/thai-central_299998_mic1.flac probably does not have speech please check it !!

Processing files:  41%|████▏     | 92842/225028 [2:55:52<3:00:15, 12.22it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0503/thai-central_143296_mic1.flac probably does not have speech please check it !!

Processing files:  41%|████▏     | 93200/225028 [2:56:33<2:52:28, 12.74it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0185/thai-central_081055_mic1.flac probably does not have speech please check it !!

Processing files:  42%|████▏     | 93562/225028 [2:57:10<4:40:21,  7.82it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0300/thai-central_430014_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99830/225028 [3:08:48<6:28:53,  5.37it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_303088_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99836/225028 [3:08:49<5:59:37,  5.80it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_249116_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99851/225028 [3:08:50<3:32:55,  9.80it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_427070_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_424277_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99861/225028 [3:08:52<4:19:03,  8.05it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_413301_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_225332_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99868/225028 [3:08:52<3:49:07,  9.10it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_098966_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_205343_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99903/225028 [3:08:57<4:08:34,  8.39it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_433077_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99928/225028 [3:09:00<4:27:11,  7.80it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_265241_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_259282_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99932/225028 [3:09:01<3:39:11,  9.51it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_326135_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99949/225028 [3:09:03<5:28:05,  6.35it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_208439_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99955/225028 [3:09:04<5:36:27,  6.20it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_138660_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99959/225028 [3:09:05<4:49:25,  7.20it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_177583_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99963/225028 [3:09:05<5:46:50,  6.01it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_043835_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99969/225028 [3:09:07<6:23:24,  5.44it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_296630_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99979/225028 [3:09:08<4:20:59,  7.99it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_413316_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_065370_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99985/225028 [3:09:09<4:47:30,  7.25it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_285970_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99991/225028 [3:09:09<4:20:18,  8.01it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_153096_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 99997/225028 [3:09:10<3:52:27,  8.96it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_216019_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100011/225028 [3:09:12<3:30:27,  9.90it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_265162_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_350939_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100015/225028 [3:09:12<3:21:11, 10.36it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_226208_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100021/225028 [3:09:13<3:20:39, 10.38it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_143080_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100025/225028 [3:09:13<3:11:05, 10.90it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_217403_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100028/225028 [3:09:13<4:07:19,  8.42it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_107419_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100032/225028 [3:09:14<4:18:04,  8.07it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_389883_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_281185_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100045/225028 [3:09:15<3:22:41, 10.28it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_399676_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100058/225028 [3:09:17<4:24:51,  7.86it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_187931_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100061/225028 [3:09:18<5:28:15,  6.35it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_141416_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100066/225028 [3:09:18<5:14:34,  6.62it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_370828_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100074/225028 [3:09:20<4:56:19,  7.03it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_065355_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_430600_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100081/225028 [3:09:21<4:25:06,  7.85it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_200241_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100085/225028 [3:09:21<4:12:08,  8.26it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_204539_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100099/225028 [3:09:23<3:57:48,  8.76it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_135235_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_019861_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100101/225028 [3:09:23<3:57:04,  8.78it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_228974_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100119/225028 [3:09:25<3:31:35,  9.84it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_358128_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_009284_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100128/225028 [3:09:26<5:24:59,  6.41it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_393717_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100134/225028 [3:09:27<4:13:34,  8.21it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_098261_mic1.flac probably does not have speech please check it !!

Processing files:  44%|████▍     | 100136/225028 [3:09:27<3:57:55,  8.75it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_238922_mic1.flac probably does not have speech please check it !!

Processing files:  45%|████▍     | 100138/225028 [3:09:27<3:57:10,  8.78it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0812/thai-central_169375_mic1.flac probably does not have speech please check it !!

Processing files:  45%|████▌     | 102087/225028 [3:13:23<3:58:16,  8.60it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0762/thai-central_260428_mic1.flac probably does not have speech please check it !!

Processing files:  45%|████▌     | 102363/225028 [3:14:01<7:05:29,  4.80it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0741/thai-central_185504_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105578/225028 [3:20:11<3:26:54,  9.62it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_404908_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_373725_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105581/225028 [3:20:11<4:26:40,  7.47it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_292826_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_183445_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105583/225028 [3:20:12<4:20:52,  7.63it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_377490_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_202916_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_189850_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105585/225028 [3:20:12<4:39:33,  7.12it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_336735_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_020091_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105587/225028 [3:20:12<4:54:33,  6.76it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_113000_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105588/225028 [3:20:13<5:35:54,  5.93it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_065492_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105590/225028 [3:20:13<6:20:44,  5.23it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_165045_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_017995_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105591/225028 [3:20:13<6:31:46,  5.08it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_101090_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105592/225028 [3:20:14<7:24:52,  4.47it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_341925_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105594/225028 [3:20:14<7:30:51,  4.42it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_064806_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_054411_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105595/225028 [3:20:14<8:29:44,  3.91it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_208803_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105596/225028 [3:20:15<8:38:19,  3.84it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_148655_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105598/225028 [3:20:15<7:42:58,  4.30it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_220892_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_034776_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105600/225028 [3:20:15<7:04:32,  4.69it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_103367_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_423380_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105601/225028 [3:20:16<8:35:28,  3.86it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_412107_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105603/225028 [3:20:16<7:20:44,  4.52it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_102869_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_059534_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105604/225028 [3:20:17<9:18:41,  3.56it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_031382_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105605/225028 [3:20:17<9:57:02,  3.33it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_261462_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105606/225028 [3:20:17<9:52:16,  3.36it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_097215_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_082423_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105608/225028 [3:20:18<8:11:03,  4.05it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_039239_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105609/225028 [3:20:18<7:54:08,  4.20it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_160222_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105610/225028 [3:20:18<8:06:13,  4.09it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_033078_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105612/225028 [3:20:19<7:58:26,  4.16it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_029270_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_046983_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105613/225028 [3:20:19<7:26:30,  4.46it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_122004_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_372198_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105615/225028 [3:20:19<6:16:46,  5.28it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_306668_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105617/225028 [3:20:19<5:40:13,  5.85it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_311767_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_195674_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105619/225028 [3:20:20<5:31:11,  6.01it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_142406_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_181175_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_403564_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105622/225028 [3:20:20<5:51:11,  5.67it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_156817_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_419265_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105624/225028 [3:20:21<5:43:13,  5.80it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_082510_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_388929_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105625/225028 [3:20:21<6:34:34,  5.04it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_017324_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105626/225028 [3:20:21<6:41:56,  4.95it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_271610_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_175083_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105630/225028 [3:20:22<5:08:28,  6.45it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_036326_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_191151_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_264327_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105632/225028 [3:20:22<4:46:09,  6.95it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_393531_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_422169_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105634/225028 [3:20:22<5:00:46,  6.62it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_225225_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_362497_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105636/225028 [3:20:23<7:13:56,  4.59it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_096372_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_423263_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105638/225028 [3:20:23<5:22:58,  6.16it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_349638_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_047883_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105639/225028 [3:20:23<5:07:35,  6.47it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_366703_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105640/225028 [3:20:23<5:51:32,  5.66it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_029282_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_089667_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105643/225028 [3:20:24<6:08:24,  5.40it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_062426_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_061732_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105644/225028 [3:20:24<6:06:50,  5.42it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_337250_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105646/225028 [3:20:25<6:29:28,  5.11it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_326674_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_018856_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105648/225028 [3:20:25<5:14:03,  6.34it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_203651_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_070382_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105649/225028 [3:20:25<5:02:35,  6.58it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_257250_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105651/225028 [3:20:25<5:07:32,  6.47it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_314682_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_363583_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105653/225028 [3:20:26<5:09:03,  6.44it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_398208_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_159983_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105655/225028 [3:20:26<4:49:48,  6.87it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_217187_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_403634_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105657/225028 [3:20:26<5:12:09,  6.37it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_398512_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_413944_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105660/225028 [3:20:27<4:58:57,  6.65it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_288130_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_370485_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_329355_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105662/225028 [3:20:27<4:42:12,  7.05it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_171756_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_332410_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105663/225028 [3:20:27<4:55:46,  6.73it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_382074_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_403982_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105666/225028 [3:20:28<4:56:24,  6.71it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_041929_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_398140_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105667/225028 [3:20:28<5:04:39,  6.53it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_188081_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_041688_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105670/225028 [3:20:28<5:01:31,  6.60it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_421293_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_023058_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105673/225028 [3:20:29<4:20:04,  7.65it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_232855_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_387645_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_139513_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105675/225028 [3:20:29<4:33:59,  7.26it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_425227_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_271948_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105676/225028 [3:20:29<4:33:02,  7.29it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_064116_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_297321_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105678/225028 [3:20:29<4:30:14,  7.36it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_211069_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105679/225028 [3:20:30<5:59:56,  5.53it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_002902_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105681/225028 [3:20:30<6:32:41,  5.07it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_155099_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_323278_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105682/225028 [3:20:30<6:20:54,  5.22it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_328356_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105684/225028 [3:20:31<7:06:25,  4.66it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_370169_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_246346_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105686/225028 [3:20:31<5:19:07,  6.23it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_152549_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_136794_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_003434_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105688/225028 [3:20:31<4:43:15,  7.02it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_402021_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105690/225028 [3:20:32<5:26:14,  6.10it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_183888_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_392608_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105691/225028 [3:20:32<7:05:11,  4.68it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_073186_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105692/225028 [3:20:32<7:10:50,  4.62it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_265250_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105694/225028 [3:20:33<7:07:31,  4.65it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_253328_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_185316_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105695/225028 [3:20:33<7:50:45,  4.22it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_382842_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105698/225028 [3:20:34<6:20:11,  5.23it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_148793_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_271257_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_338421_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105699/225028 [3:20:34<7:02:38,  4.71it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_166856_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105701/225028 [3:20:34<7:04:52,  4.68it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_358894_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_136795_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105703/225028 [3:20:35<8:12:22,  4.04it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_143898_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_191614_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105705/225028 [3:20:35<6:24:46,  5.17it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_099352_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_152404_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105708/225028 [3:20:36<4:34:47,  7.24it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_066905_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_376578_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_334421_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105710/225028 [3:20:36<5:41:40,  5.82it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_152859_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_136888_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105711/225028 [3:20:36<5:28:11,  6.06it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_255559_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_407347_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105715/225028 [3:20:37<5:06:06,  6.50it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_225751_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_120020_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_254592_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105716/225028 [3:20:37<4:47:28,  6.92it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_005114_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105719/225028 [3:20:37<4:55:06,  6.74it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_206235_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_187778_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_405788_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105720/225028 [3:20:38<5:23:32,  6.15it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_101069_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_255227_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105722/225028 [3:20:38<4:40:21,  7.09it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_341951_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105723/225028 [3:20:38<5:43:36,  5.79it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_217499_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105725/225028 [3:20:39<6:00:14,  5.52it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_268073_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_387566_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105727/225028 [3:20:39<4:46:10,  6.95it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_078792_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_199536_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105729/225028 [3:20:39<5:18:53,  6.24it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_151871_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_356888_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105732/225028 [3:20:40<5:04:52,  6.52it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_212426_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_113656_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_318906_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105734/225028 [3:20:40<5:07:01,  6.48it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_072283_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_369522_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105736/225028 [3:20:40<5:35:40,  5.92it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_260537_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_069816_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105738/225028 [3:20:41<4:45:33,  6.96it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_151834_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_133710_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105740/225028 [3:20:41<4:28:46,  7.40it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_398194_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_012349_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105741/225028 [3:20:41<5:20:48,  6.20it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_424477_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105743/225028 [3:20:42<6:34:34,  5.04it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_270264_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_421391_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105745/225028 [3:20:42<5:51:45,  5.65it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_349678_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_252266_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105746/225028 [3:20:42<5:18:39,  6.24it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_393841_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105748/225028 [3:20:42<6:18:37,  5.25it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_154298_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_274588_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105749/225028 [3:20:43<6:04:49,  5.45it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_253785_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_129691_mic1.flac probably does not have speech please check it !!

Processing files:  47%|████▋     | 105753/225028 [3:20:43<4:45:50,  6.95it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0441/thai-central_147704_mic1.flac probably does not have speech please check it !!

Processing files:  49%|████▉     | 110312/225028 [3:29:30<1:31:58, 20.79it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0679/thai-central_370105_mic1.flac probably does not have speech please check it !!

Processing files:  51%|█████▏    | 115743/225028 [3:38:42<2:21:15, 12.89it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0505/thai-central_346004_mic1.flac probably does not have speech please check it !!

Processing files:  53%|█████▎    | 118404/225028 [3:43:01<3:00:01,  9.87it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0056/thai-central_156639_mic1.flac probably does not have speech please check it !!

Processing files:  53%|█████▎    | 118837/225028 [3:43:49<2:39:29, 11.10it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0724/thai-central_174965_mic1.flac probably does not have speech please check it !!

Processing files:  53%|█████▎    | 119459/225028 [3:45:05<3:26:20,  8.53it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0098/thai-central_333028_mic1.flac probably does not have speech please check it !!

Processing files:  53%|█████▎    | 119919/225028 [3:46:12<2:59:27,  9.76it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0645/thai-central_161543_mic1.flac probably does not have speech please check it !!

Processing files:  54%|█████▍    | 121229/225028 [3:48:49<4:08:44,  6.95it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0259/thai-central_171994_mic1.flac probably does not have speech please check it !!

Processing files:  54%|█████▍    | 121416/225028 [3:49:13<3:28:57,  8.26it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0677/thai-central_086411_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125342/225028 [3:56:29<2:11:01, 12.68it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_246074_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_337766_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_349907_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_345885_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_178142_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125348/225028 [3:56:30<1:48:00, 15.38it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_163257_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_405089_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_196035_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_054389_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_091267_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_176368_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125354/225028 [3:56:30<1:28:08, 18.85it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_287209_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_099925_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_355408_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_102886_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_386873_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_000029_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125357/225028 [3:56:30<1:20:23, 20.67it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_242953_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_311809_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_263294_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_019145_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125363/225028 [3:56:31<1:26:01, 19.31it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_288811_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_429910_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125366/225028 [3:56:31<1:18:55, 21.05it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_136092_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_115349_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_067819_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_249104_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_313915_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125369/225028 [3:56:31<1:35:11, 17.45it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_027687_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_158834_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125373/225028 [3:56:31<2:32:55, 10.86it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_037555_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_069852_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125379/225028 [3:56:32<2:45:01, 10.06it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_237696_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_384074_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_401610_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_291758_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125384/225028 [3:56:33<2:18:34, 11.98it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_278133_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_317128_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_110078_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125389/225028 [3:56:33<1:47:35, 15.44it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_184350_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_414744_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_351374_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_218017_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125394/225028 [3:56:33<1:40:45, 16.48it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_207293_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_431946_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_294695_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125396/225028 [3:56:33<1:58:27, 14.02it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_175498_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_296488_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125398/225028 [3:56:34<2:38:05, 10.50it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_195791_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125402/225028 [3:56:34<3:21:53,  8.22it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_267507_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_282315_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125408/225028 [3:56:35<2:02:41, 13.53it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_365660_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_120024_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_203669_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_277458_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_110297_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125411/225028 [3:56:35<1:44:01, 15.96it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_421439_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_246766_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_236466_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_155846_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125414/225028 [3:56:35<1:31:30, 18.14it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_321826_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125421/225028 [3:56:35<1:43:36, 16.02it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_393066_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_067103_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_403323_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_345933_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125426/225028 [3:56:35<1:26:50, 19.11it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_060178_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_136586_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_134600_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_023486_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125432/225028 [3:56:36<1:18:06, 21.25it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_358017_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_412317_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_242262_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_348158_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_184950_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_193589_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_307417_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125435/225028 [3:56:36<1:17:04, 21.54it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_400646_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_100236_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_206177_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125440/225028 [3:56:36<1:45:31, 15.73it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_145643_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_232922_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_074049_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125443/225028 [3:56:36<1:42:18, 16.22it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_009298_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_208979_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_170928_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125448/225028 [3:56:37<1:49:21, 15.18it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_023271_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_283469_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125452/225028 [3:56:37<1:54:03, 14.55it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_039685_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_340201_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_340156_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_071227_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125457/225028 [3:56:37<1:41:01, 16.43it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_228873_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_249248_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_356330_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_227478_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125460/225028 [3:56:38<2:29:56, 11.07it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_216301_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125464/225028 [3:56:38<2:54:21,  9.52it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_202285_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_106697_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_209203_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125470/225028 [3:56:39<2:59:46,  9.23it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_051106_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_130302_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125472/225028 [3:56:39<2:37:55, 10.51it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_005983_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_341721_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125476/225028 [3:56:39<2:21:02, 11.76it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_201760_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_048451_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_026613_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125481/225028 [3:56:40<1:52:23, 14.76it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_017535_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_203640_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_341056_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125485/225028 [3:56:40<1:57:56, 14.07it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_238976_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_038571_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_008108_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_376808_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125490/225028 [3:56:40<1:44:41, 15.85it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_352943_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_197441_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125495/225028 [3:56:41<1:28:51, 18.67it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_005205_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_187799_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_262421_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_060083_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125500/225028 [3:56:41<1:43:25, 16.04it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_271252_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_154943_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_122795_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_094177_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_343930_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_132803_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125506/225028 [3:56:41<1:26:46, 19.11it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_418331_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_246519_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_056605_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_225979_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125509/225028 [3:56:41<1:53:36, 14.60it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_365023_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_424451_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_407187_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_115938_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125513/225028 [3:56:42<2:02:45, 13.51it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_275170_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125517/225028 [3:56:42<2:42:05, 10.23it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_344082_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_079925_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_143955_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_269603_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125523/225028 [3:56:43<2:24:26, 11.48it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_189932_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_232475_mic1.flac probably does not have speech please check it !!

Processing files:  56%|█████▌    | 125528/225028 [3:56:43<2:02:21, 13.55it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_191209_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_091918_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_094172_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0508/thai-central_121907_mic1.flac probably does not have speech please check it !!

Processing files:  58%|█████▊    | 129478/225028 [4:04:15<3:01:19,  8.78it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0848/thai-central_169415_mic1.flac probably does not have speech please check it !!

Processing files:  60%|█████▉    | 134901/225028 [4:13:52<2:20:50, 10.67it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0734/thai-central_258662_mic1.flac probably does not have speech please check it !!

Processing files:  61%|██████    | 136216/225028 [4:16:19<2:36:55,  9.43it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0882/thai-central_381914_mic1.flac probably does not have speech please check it !!

Processing files:  61%|██████    | 136469/225028 [4:16:43<1:59:54, 12.31it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0882/thai-central_216605_mic1.flac probably does not have speech please check it !!

Processing files:  63%|██████▎   | 142636/225028 [4:27:35<3:04:02,  7.46it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0180/thai-central_210575_mic1.flac probably does not have speech please check it !!

Processing files:  64%|██████▍   | 144821/225028 [4:31:33<1:23:22, 16.03it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0050/thai-central_359317_mic1.flac probably does not have speech please check it !!

Processing files:  65%|██████▍   | 146023/225028 [4:33:46<1:31:12, 14.44it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0531/thai-central_354998_mic1.flac probably does not have speech please check it !!

Processing files:  66%|██████▌   | 148479/225028 [4:38:15<2:23:13,  8.91it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0332/thai-central_090647_mic1.flac probably does not have speech please check it !!

Processing files:  67%|██████▋   | 149945/225028 [4:40:56<2:40:10,  7.81it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0796/thai-central_218200_mic1.flac probably does not have speech please check it !!

Processing files:  68%|██████▊   | 152437/225028 [4:45:23<1:06:42, 18.13it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0900/thai-central_344923_mic1.flac probably does not have speech please check it !!

Processing files:  71%|███████   | 159171/225028 [4:57:56<2:08:05,  8.57it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0510/thai-central_068154_mic1.flac probably does not have speech please check it !!

Processing files:  71%|███████   | 159962/225028 [4:59:40<1:37:34, 11.11it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0851/thai-central_077017_mic1.flac probably does not have speech please check it !!

Processing files:  72%|███████▏  | 162792/225028 [5:04:22<3:12:30,  5.39it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0169/thai-central_409699_mic1.flac probably does not have speech please check it !!

Processing files:  75%|███████▍  | 167841/225028 [5:14:32<1:00:07, 15.85it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0600/thai-central_327221_mic1.flac probably does not have speech please check it !!

Processing files:  76%|███████▌  | 171285/225028 [5:21:19<1:47:24,  8.34it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0303/thai-central_066512_mic1.flac probably does not have speech please check it !!

Processing files:  78%|███████▊  | 175989/225028 [5:31:01<52:29, 15.57it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0611/thai-central_277675_mic1.flac probably does not have speech please check it !!

Processing files:  78%|███████▊  | 176080/225028 [5:31:08<57:01, 14.31it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0611/thai-central_341197_mic1.flac probably does not have speech please check it !!

Processing files:  80%|████████  | 180902/225028 [5:39:27<1:11:29, 10.29it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0022/thai-central_231552_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185783/225028 [5:47:52<1:42:01,  6.41it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_321975_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185786/225028 [5:47:53<2:08:34,  5.09it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_353895_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185790/225028 [5:47:53<1:17:31,  8.44it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_097905_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185801/225028 [5:47:55<1:25:34,  7.64it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_275309_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185808/225028 [5:47:55<1:12:45,  8.99it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_289193_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185813/225028 [5:47:56<59:49, 10.93it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_274375_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185817/225028 [5:47:56<1:10:35,  9.26it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_064818_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185828/225028 [5:47:58<1:22:58,  7.87it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_230695_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185831/225028 [5:47:58<1:18:32,  8.32it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_120856_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185834/225028 [5:47:59<1:33:59,  6.95it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_232185_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185840/225028 [5:48:00<1:12:00,  9.07it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_354880_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_399958_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185854/225028 [5:48:01<50:05, 13.04it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_398525_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_312950_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185871/225028 [5:48:03<1:23:42,  7.80it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_105360_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185878/225028 [5:48:04<1:09:39,  9.37it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_351072_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185883/225028 [5:48:05<1:28:25,  7.38it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_425944_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185889/225028 [5:48:06<1:55:30,  5.65it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_076656_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185895/225028 [5:48:07<1:16:19,  8.55it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_295647_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_334322_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_269557_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185897/225028 [5:48:07<1:03:41, 10.24it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_230645_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_412496_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185901/225028 [5:48:07<1:09:04,  9.44it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_312963_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185905/225028 [5:48:08<59:26, 10.97it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_227447_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_359891_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185913/225028 [5:48:09<1:17:59,  8.36it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_204632_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185920/225028 [5:48:10<1:14:47,  8.71it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_389511_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185926/225028 [5:48:11<1:14:20,  8.77it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_336817_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185928/225028 [5:48:11<1:01:49, 10.54it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_267811_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_014040_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185932/225028 [5:48:11<1:13:02,  8.92it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_001801_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_383083_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185937/225028 [5:48:12<1:21:51,  7.96it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_001856_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185941/225028 [5:48:13<1:22:08,  7.93it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_360507_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185950/225028 [5:48:14<1:14:04,  8.79it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_118142_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185956/225028 [5:48:15<1:24:24,  7.72it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_076021_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185971/225028 [5:48:17<1:37:12,  6.70it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_134172_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_245421_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185977/225028 [5:48:18<1:21:41,  7.97it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_415537_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_211571_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_274156_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185980/225028 [5:48:18<1:19:54,  8.14it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_120193_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185982/225028 [5:48:19<1:31:33,  7.11it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_200601_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 185993/225028 [5:48:20<1:09:28,  9.36it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_169110_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_421613_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 186001/225028 [5:48:21<1:02:03, 10.48it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_175030_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_330461_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 186003/225028 [5:48:21<1:26:26,  7.52it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_221276_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 186008/225028 [5:48:22<1:10:20,  9.25it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_181383_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_045367_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 186012/225028 [5:48:22<1:05:46,  9.89it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_015570_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 186016/225028 [5:48:23<1:13:06,  8.89it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_358304_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_205207_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 186019/225028 [5:48:23<1:16:34,  8.49it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_420054_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_108332_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 186025/225028 [5:48:24<1:44:46,  6.20it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_205741_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 186030/225028 [5:48:25<1:25:58,  7.56it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_368341_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 186034/225028 [5:48:25<1:05:14,  9.96it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_194618_mic1.flac probably does not have speech please check it !!
> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_213885_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 186038/225028 [5:48:26<1:03:19, 10.26it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_197312_mic1.flac probably does not have speech please check it !!

Processing files:  83%|████████▎ | 186042/225028 [5:48:26<1:11:07,  9.13it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0698/thai-central_331921_mic1.flac probably does not have speech please check it !!

Processing files:  88%|████████▊ | 197108/225028 [6:07:57<43:39, 10.66it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0494/thai-central_357219_mic1.flac probably does not have speech please check it !!

Processing files:  88%|████████▊ | 197803/225028 [6:09:17<48:05,  9.44it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0007/thai-central_197692_mic1.flac probably does not have speech please check it !!

Processing files:  92%|█████████▏| 206015/225028 [6:24:08<20:12, 15.68it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0895/thai-central_406211_mic1.flac probably does not have speech please check it !!

Processing files:  95%|█████████▌| 214165/225028 [6:38:59<22:22,  8.09it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0785/thai-central_368289_mic1.flac probably does not have speech please check it !!

Processing files:  96%|█████████▌| 215086/225028 [6:40:35<15:02, 11.02it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0885/thai-central_297606_mic1.flac probably does not have speech please check it !!

Processing files:  97%|█████████▋| 217298/225028 [6:44:35<12:34, 10.24it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0957/thai-central_040425_mic1.flac probably does not have speech please check it !!

Processing files:  98%|█████████▊| 219643/225028 [6:48:25<08:03, 11.15it/s]

> The file ../data/converted/thai-central-to-vctk/wav16_silence_trimmed/tc0616/thai-central_141438_mic1.flac probably does not have speech please check it !!

Processing files: 100%|██████████| 225028/225028 [6:57:21<00:00,  8.99it/s]

Processing complete

Found 523 files with no speech. List saved to ../data/converted/thai-central-to-vctk/no_speech_files.txt

In [13]:
# Normalize the volume of all audio files to -27dB
normalize_audio_files(dst_dir, "flac", -27, 16000)

Normalizing audio files: 100%|██████████| 225028/225028 [14:23:45<00:00,  4.34it/s]